### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@benoitf Can you please review and merge? That fixes all 5 current open issues, enable much more usability.

**Comment by benoitf** [comment]
@mickaelistria do you have more changes on the way ?

**Comment by mickaelistria** [comment]
This patch is good for now, you can merge it thanks.
Some further work is happening and will be the topic of some other patches in the future probably.

**Comment by mickaelistria** [comment]
Do you push it manually? I don't see an autobuild for it at https://hub.docker.com/r/wsskeleton/eclipse-broadway/builds (but IIRC, docker hub had some autobuilds vanishing lately)

**Comment by benoitf** [comment]
image


automatic build

**Pull request merged**
